[build]
  publish = "exampleSite/public"
  command = "hugo --port 8080 --bind 0.0.0.0 --renderToDisk -d public"
  
[build.environment]
  HUGO_VERSION = "0.86.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"